version: '1.0'

services:
  qdrant:
    platform: linux/amd64
    image: qdrant/qdrant
#    command: bash
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "6333:6333"
      - "6334:6334"
